global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

rule_files:
  - "rules/*.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'apache'
    static_configs:
      - targets: ['web:80']
    metrics_path: '/metrics'

  - job_name: 'jenkins'
    metrics_path: '/jenkins/prometheus'
    static_configs:
      - targets: ['jenkins:8080']

  - job_name: 'docker'
    static_configs:
      - targets: ['docker:9323']